name: 'Create release'
on:
  push:
    branches:
      - 'main'

jobs:
  prepare:
    name: Latest commit
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.latest_commit.outputs.commit }}
    steps:
    - name: Clone 
      uses: actions/checkout@v4

    - name: Set latest_commit
      id: latest_commit
      run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
  
  release:
    name: Create GitHub Release
    needs: [prepare]
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
      if: github.event_name != 'push'

    - name: Set tag name
      id: tag
      run: |
        if [[ "${{ github.event_name }}" != "push" ]]; then
          tag=v$(date +%Y%m%d.%H%M%S)
        else
          tag=$(basename "${{ github.ref }}")
        fi
        echo "tag=$tag" >> $GITHUB_OUTPUT
    
    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        tag="${{ steps.tag.outputs.tag }}"
        body="RaidTeamDecorator@${{ needs.prepare.outputs.commit }}"
        gh release create --draft "$tag" --title "$tag" --notes "$body"
  build:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    
    - name: Zip Folder
      run: |
        cd ../
        rm -rf RaidTeamDecorator.zip
        zip -r RaidTeamDecorator${{ needs.release.outputs.tag }}.zip RaidTeamDecorator -x "RaidTeamDecorator/.git/*" "RaidTeamDecorator/.github/*"

    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        cd ../
        gh release upload "${{ needs.release.outputs.tag }}" "RaidTeamDecorator${{ needs.release.outputs.tag }}.zip"

  publish:
    name: Publish Release
    needs: [release, build]
    runs-on: ubuntu-latest
    environment: Release
    steps:
    - name: Publish Release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release edit "${{ needs.release.outputs.tag }}" --draft=false
